version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: option_backend
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - LONGPORT_APP_KEY=${LONGPORT_APP_KEY}
      - LONGPORT_APP_SECRET=${LONGPORT_APP_SECRET}
      - LONGPORT_ACCESS_TOKEN=${LONGPORT_ACCESS_TOKEN}
      - LONGPORT_REGION=${LONGPORT_REGION}
    ports:
      - "14086:14086"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - option_network

  # 前端服务
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: option_frontend
    restart: always
    ports:
      - "6688:6688"
    depends_on:
      - backend
    networks:
      - option_network

networks:
  option_network:
    driver: bridge 